import pandas as pd
from collections import Counter
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

def generate_kb_suggestions():
    df = pd.read_csv(BASE_DIR / 'compras_saneada.csv')
    
    # Contar termos mais comuns para criar o palavras.csv
    descriptions = df['descricao_normalizada'].tolist()
    
    # Mapeamento manual inicial baseado na análise da planilha
    kb_palavras = [
        ('uber', 'Uber'),
        ('99app', '99'),
        ('99 volta', '99'),
        ('99 ida', '99'),
        ('ifood', 'iFood'),
        ('amazon prime', 'Amazon Prime'),
        ('netflix', 'Netflix'),
        ('spotify', 'Spotify'),
        ('hbo max', 'HBO Max'),
        ('mercado', 'Mercado'),
        ('pao de acucar', 'Pão de Açúcar'),
        ('st marche', 'St Marche'),
        ('savegnago', 'Savegnago'),
        ('carrefour', 'Carrefour'),
        ('mcdonald', 'McDonald\'s'),
        ('bk', 'Burger King'),
        ('burger', 'Hamburgueria'),
        ('pizza', 'Pizza'),
        ('barbeiro', 'Barbearia'),
        ('barbearia', 'Barbearia'),
        ('academia', 'Academia'),
        ('farmacia', 'Saúde'),
        ('remedio', 'Saúde'),
        ('vivo', 'Telefonia'),
        ('condominio', 'Casa'),
        ('aluguel', 'Casa'),
        ('energia', 'Casa'),
        ('internet', 'Casa'),
        ('onibus', 'Transporte'),
        ('passagem', 'Viagem'),
        ('blablacar', 'Transporte'),
        ('carona', 'Transporte'),
        ('shopee', 'Compras'),
        ('aliexpress', 'Compras'),
        ('americanas', 'Compras'),
        ('renner', 'Vestuário'),
        ('daiso', 'Casa'),
        ('posto', 'Transporte'),
        ('combustivel', 'Transporte'),
        ('cinema', 'Lazer'),
        ('ingresso', 'Lazer'),
        ('hospedagem', 'Viagem'),
        ('hotel', 'Viagem'),
        ('restaurante', 'Restaurante'),
        ('self service', 'Restaurante'),
        ('japa', 'Restaurante'),
        ('sushi', 'Restaurante'),
        ('hamburguer', 'Fast Food'),
        ('lanche', 'Restaurante'),
        ('cerveja', 'Lazer'),
        ('bebida', 'Lazer'),
        ('presente', 'Lazer'),
        ('cadeira', 'Casa'),
        ('tenis', 'Vestuário'),
        ('roupa', 'Vestuário'),
        ('camisa', 'Vestuário'),
        ('camiseta', 'Vestuário'),
        ('convite', 'Lazer'),
        ('formatura', 'Lazer'),
        ('medico', 'Saúde'),
        ('dentista', 'Saúde'),
        ('pix', 'Transferência'),
        ('transferencia', 'Transferência'),
        ('uber', 'Uber'),
        ('99', '99'),
        ('ifood', 'iFood'),
        ('borelli', 'Restaurante'),
        ('brazukis', 'Restaurante'),
        ('kabup', 'Restaurante'),
        ('cookie', 'Restaurante'),
        ('marmita', 'Restaurante'),
        ('pizza', 'Pizza'),
        ('burger', 'Hamburgueria'),
        ('cafe', 'Restaurante'),
        ('doce', 'Restaurante'),
        ('sorvete', 'Restaurante'),
        ('milk shake', 'Restaurante'),
        ('pao', 'Mercado'),
        ('mercado', 'Mercado'),
        ('supermercado', 'Mercado'),
        ('compras', 'Mercado'),
        ('st marche', 'St Marche'),
        ('pao de acucar', 'Pão de Açúcar'),
        ('savegnago', 'Savegnago'),
        ('carrefour', 'Carrefour'),
        ('daiso', 'Casa'),
        ('amazon', 'Amazon'),
        ('netflix', 'Netflix'),
        ('spotify', 'Spotify'),
        ('hbo', 'HBO'),
        ('disney', 'Disney+'),
        ('apple', 'Apple'),
        ('google', 'Google'),
        ('clube', 'Assinaturas'),
        ('assinatura', 'Assinaturas'),
        ('prime', 'Amazon Prime'),
        ('vivo', 'Telefonia'),
        ('claro', 'Telefonia'),
        ('tim', 'Telefonia'),
        ('oi', 'Telefonia'),
        ('condominio', 'Casa'),
        ('aluguel', 'Casa'),
        ('energia', 'Casa'),
        ('luz', 'Casa'),
        ('agua', 'Casa'),
        ('internet', 'Casa'),
        ('onibus', 'Transporte'),
        ('metro', 'Transporte'),
        ('trem', 'Transporte'),
        ('passagem', 'Viagem'),
        ('viagem', 'Viagem'),
        ('hotel', 'Viagem'),
        ('pousada', 'Viagem'),
        ('airbnb', 'Viagem'),
        ('shopee', 'Compras'),
        ('aliexpress', 'Compras'),
        ('magalu', 'Compras'),
        ('mercado livre', 'Compras'),
        ('mercadolivre', 'Compras'),
        ('americanas', 'Compras'),
        ('renner', 'Vestuário'),
        ('c&a', 'Vestuário'),
        ('cea', 'Vestuário'),
        ('riachuelo', 'Vestuário'),
        ('zara', 'Vestuário'),
        ('posto', 'Transporte'),
        ('shell', 'Transporte'),
        ('ipiranga', 'Transporte'),
        ('br', 'Transporte'),
        ('combustivel', 'Transporte'),
        ('gasolina', 'Transporte'),
        ('cinema', 'Lazer'),
        ('ingresso', 'Lazer'),
        ('show', 'Lazer'),
        ('teatro', 'Lazer'),
        ('museu', 'Lazer'),
        ('parque', 'Lazer'),
        ('viagem', 'Viagem'),
        ('hospedagem', 'Viagem'),
        ('restaurante', 'Restaurante'),
        ('churrascaria', 'Restaurante'),
        ('padaria', 'Restaurante'),
        ('bar', 'Lazer'),
        ('boteco', 'Lazer'),
        ('pub', 'Lazer'),
        ('copa', 'Lazer'),
        ('futebol', 'Lazer'),
        ('estacionamento', 'Transporte'),
        ('pedagio', 'Transporte'),
        ('uber', 'Uber'),
        ('99', '99'),
        ('cabify', 'Transporte'),
        ('coca', 'Restaurante'),
        ('chopp', 'Lazer'),
        ('vinho', 'Lazer'),
        ('livro', 'Lazer'),
        ('salgado', 'Restaurante'),
        ('esfiha', 'Fast Food'),
        ('habibs', 'Fast Food'),
        ('toninho', 'Restaurante'),
        ('paru', 'Restaurante'),
        ('tulipa', 'Lazer'),
        ('energetico', 'Lazer'),
        ('guaruja', 'Viagem'),
        ('santos', 'Viagem'),
        ('campos', 'Viagem'),
        ('isqueiro', 'Outros'),
        ('queijo', 'Mercado'),
        ('pastel', 'Restaurante'),
        ('paintball', 'Lazer'),
        ('fondue', 'Restaurante'),
        ('maca', 'Mercado'),
        ('banana', 'Mercado'),
        ('fruta', 'Mercado'),
        ('carne', 'Mercado'),
        ('açougue', 'Mercado'),
        ('farmacia', 'Saúde'),
        ('droga', 'Saúde'),
        ('raçao', 'Casa'),
        ('gato', 'Casa'),
        ('pet', 'Casa'),
        ('veterinario', 'Saúde'),
        ('estacionamento', 'Transporte'),
        ('pedagio', 'Transporte'),
        ('sem parar', 'Transporte'),
        ('veloe', 'Transporte'),
        ('tag', 'Transporte'),
        ('revisao', 'Transporte'),
        ('mecanico', 'Transporte'),
        ('pneu', 'Transporte'),
        ('oleo', 'Transporte'),
        ('lavagem', 'Transporte'),
        ('ipva', 'Transporte'),
        ('seguro', 'Serviços'),
        ('imposto', 'Serviços'),
        ('tarifa', 'Serviços'),
        ('taxa', 'Serviços'),
        ('mensalidade', 'Assinaturas'),
        ('curso', 'Educação'),
        ('escola', 'Educação'),
        ('faculdade', 'Educação'),
        ('livro', 'Educação'),
        ('material', 'Educação'),
        ('papelaria', 'Educação'),
        ('presente', 'Lazer'),
        ('flores', 'Lazer'),
        ('cinema', 'Lazer'),
        ('streaming', 'Assinaturas'),
        ('jogo', 'Lazer'),
        ('game', 'Lazer'),
        ('steam', 'Lazer'),
        ('psn', 'Lazer'),
        ('xbox', 'Lazer'),
        ('brinquedo', 'Lazer'),
        ('viagem', 'Viagem'),
        ('uber', 'Uber'),
        ('99', '99'),
        ('ifood', 'iFood'),
        ('rappi', 'Delivery'),
        ('delivery', 'Delivery'),
        ('comida', 'Restaurante'),
        ('almoco', 'Restaurante'),
        ('jantar', 'Restaurante'),
        ('cafe', 'Restaurante'),
        ('padaria', 'Restaurante'),
        ('confeitaria', 'Restaurante'),
        ('sorvete', 'Restaurante'),
        ('acai', 'Restaurante'),
        ('suco', 'Restaurante'),
        ('agua', 'Mercado'),
        ('cerveja', 'Lazer'),
        ('vinho', 'Lazer'),
        ('whisky', 'Lazer'),
        ('gin', 'Lazer'),
        ('vodka', 'Lazer'),
        ('refrigerante', 'Mercado'),
        ('limpeza', 'Casa'),
        ('higiene', 'Mercado'),
        ('perfumaria', 'Lazer'),
        ('cosmetico', 'Lazer'),
        ('maquiagem', 'Lazer'),
        ('cabelo', 'Serviços'),
        ('unha', 'Serviços'),
        ('massagem', 'Saúde'),
        ('terapia', 'Saúde'),
        ('psicologo', 'Saúde'),
        ('exame', 'Saúde'),
        ('hospital', 'Saúde'),
        ('clinica', 'Saúde'),
        ('mo', 'Outros'),
        ('mae', 'Outros'),
        ('pai', 'Outros'),
        ('papai', 'Outros'),
        ('corcovado', 'Viagem'),
        ('chocolate', 'Restaurante'),
        ('smash', 'Fast Food'),
        ('celular', 'Eletrônicos'),
        ('stanley', 'Casa'),
        ('samba', 'Lazer'),
        ('seda', 'Outros'),
        ('sabonete', 'Mercado'),
        ('durex', 'Casa'),
        ('bolha', 'Casa'),
        ('reembolso', 'Transferência'),
        ('vaca', 'Restaurante'),
        ('porçao', 'Restaurante'),
        ('cachorro quente', 'Fast Food'),
        ('caipira', 'Restaurante'),
        ('festa', 'Lazer'),
        ('caipirinha', 'Lazer'),
        ('praia', 'Viagem'),
        ('short', 'Vestuário'),
        ('uniforme', 'Vestuário'),
        ('caneco', 'Lazer'),
        ('garrafa', 'Casa'),
        ('termica', 'Casa'),
        ('lingua', 'Saúde'),
        ('rap10', 'Mercado'),
        ('starbucks', 'Restaurante'),
        ('mizuno', 'Vestuário'),
        ('balance', 'Vestuário'),
        ('panela', 'Casa'),
        ('chou', 'Restaurante'),
        ('mandue', 'Restaurante')
    ]
    
    df_palavras = pd.DataFrame(kb_palavras, columns=['palavra', 'estabelecimento'])
    df_palavras.to_csv(BASE_DIR / 'palavras.csv', index=False, encoding='utf-8-sig')
    
    # Mapeamento de estabelecimentos para categorias
    kb_estabelecimentos = [
        ('Uber', 'Transporte', 'Uber'),
        ('99', 'Transporte', '99'),
        ('iFood', 'Delivery', 'iFood'),
        ('Amazon Prime', 'Assinaturas', 'Streaming'),
        ('Netflix', 'Assinaturas', 'Streaming'),
        ('Spotify', 'Assinaturas', 'Música'),
        ('HBO Max', 'Assinaturas', 'Streaming'),
        ('Pão de Açúcar', 'Mercado', 'Supermercado'),
        ('St Marche', 'Mercado', 'Supermercado'),
        ('Savegnago', 'Mercado', 'Supermercado'),
        ('Carrefour', 'Mercado', 'Supermercado'),
        ('McDonald\'s', 'Fast Food', 'Hamburgueria'),
        ('Burger King', 'Fast Food', 'Hamburgueria'),
        ('Pizza', 'Restaurante', 'Pizza'),
        ('Hamburgueria', 'Restaurante', 'Hamburgueria'),
        ('Barbearia', 'Serviços', 'Estética'),
        ('Academia', 'Saúde', 'Academia'),
        ('Saúde', 'Saúde', 'Farmácia'),
        ('Telefonia', 'Serviços', 'Telefonia'),
        ('Casa', 'Casa', 'Moradia'),
        ('Transporte', 'Transporte', 'Geral'),
        ('Viagem', 'Viagem', 'Geral'),
        ('Compras', 'Lazer', 'E-commerce'),
        ('Vestuário', 'Lazer', 'Roupas'),
        ('Lazer', 'Lazer', 'Geral'),
        ('Restaurante', 'Restaurante', 'Geral'),
        ('Fast Food', 'Fast Food', 'Geral'),
        ('Transferência', 'Serviços', 'Transferência'),
        ('Amazon', 'Lazer', 'E-commerce'),
        ('Disney+', 'Assinaturas', 'Streaming'),
        ('Apple', 'Assinaturas', 'Serviços Cloud'),
        ('Google', 'Assinaturas', 'Serviços Cloud'),
        ('Assinaturas', 'Assinaturas', 'Geral'),
        ('Eletrônicos', 'Lazer', 'Eletrônicos'),
        ('Outros', 'Outros', 'Geral')
    ]
    
    df_estab = pd.DataFrame(kb_estabelecimentos, columns=['estabelecimento', 'categoria', 'subcategoria'])
    df_estab.to_excel(BASE_DIR / 'estabelecimentos.xlsx', index=False) # Temp para conferência
    df_estab.to_csv(BASE_DIR / 'estabelecimentos.csv', index=False, encoding='utf-8-sig')

if __name__ == "__main__":
    generate_kb_suggestions()
